//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omni.Agence.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        public Adresse()
        {
            this.Locals = new HashSet<Local>();
            this.Personnes = new HashSet<Personne>();
            this.Syndics = new HashSet<Syndic>();
            this.Immeubles = new HashSet<Immeuble>();
        }
    
        public int NumAdresse { get; set; }
        public string Pays { get; set; }
        public string Ville { get; set; }
        public string quartier { get; set; }
        public string descAdresse { get; set; }
        public Nullable<int> CPadress { get; set; }
    
        public virtual ICollection<Local> Locals { get; set; }
        public virtual ICollection<Personne> Personnes { get; set; }
        public virtual ICollection<Syndic> Syndics { get; set; }
        public virtual ICollection<Immeuble> Immeubles { get; set; }
    }
}
