//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omni.Agence.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Augementation
    {
        public int idAug { get; set; }
        public Nullable<System.DateTime> dateAug { get; set; }
        public Nullable<int> pcAug { get; set; }
        public Nullable<int> CodeContrat { get; set; }
        public Nullable<int> CodePers { get; set; }
        public Nullable<int> CodeLocal { get; set; }
    
        public virtual ContratLocation ContratLocation { get; set; }
    }
}
