//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omni.Agence.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concierge
    {
        public Concierge()
        {
            this.Immeubles = new HashSet<Immeuble>();
        }
    
        public int NumConcierge { get; set; }
        public string NomConci { get; set; }
        public string PrenomConci { get; set; }
        public string CinConci { get; set; }
        public Nullable<double> SalaireConci { get; set; }
        public string TelConci { get; set; }
    
        public virtual ICollection<Immeuble> Immeubles { get; set; }
    }
}
