//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omni.Agence.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratLocation
    {
        public ContratLocation()
        {
            this.PaiementLoyers = new HashSet<PaiementLoyer>();
            this.Augementations = new HashSet<Augementation>();
        }
    
        public int CodePers { get; set; }
        public int CodeLocal { get; set; }
        public int CodeContrat { get; set; }
        public Nullable<System.DateTime> DateJuissance { get; set; }
        public Nullable<int> Usage { get; set; }
        public Nullable<double> LoyerDebase { get; set; }
        public Nullable<int> isClosed { get; set; }
        public Nullable<System.DateTime> dateClose { get; set; }
        public Nullable<int> Charge { get; set; }
        public Nullable<int> TaxeDedilite { get; set; }
        public Nullable<int> Garage { get; set; }
        public Nullable<double> LoyerNet { get; set; }
        public Nullable<int> Caution { get; set; }
        public Nullable<System.DateTime> DateFinContrat { get; set; }
        public Nullable<int> FrequencePaiement { get; set; }
        public Nullable<int> adults { get; set; }
        public Nullable<int> enfants { get; set; }
        public Nullable<bool> animaux { get; set; }
        public string commentaire { get; set; }
        public Nullable<System.DateTime> dateModification { get; set; }
    
        public virtual Local Local { get; set; }
        public virtual Personne Personne { get; set; }
        public virtual ICollection<PaiementLoyer> PaiementLoyers { get; set; }
        public virtual ICollection<Augementation> Augementations { get; set; }
    }
}
