//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omni.Agence.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depense
    {
        public int codeOp { get; set; }
        public Nullable<int> CodeImmeuble { get; set; }
        public Nullable<int> CodeLocal { get; set; }
        public int NumTypeDesignationDespense { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateDepense { get; set; }
        public Nullable<System.DateTime> DateFact { get; set; }
    
        public virtual Local Local { get; set; }
        public virtual TypeDesignationDepense TypeDesignationDepense { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual Immeuble Immeuble { get; set; }
    }
}
