//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omni.Agence.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        public Local()
        {
            this.ContratLocations = new HashSet<ContratLocation>();
            this.Depenses = new HashSet<Depense>();
        }
    
        public int CodeLocal { get; set; }
        public int NumTypeLocal { get; set; }
        public int NumAdresse { get; set; }
        public Nullable<int> CodeImmeuble { get; set; }
        public Nullable<int> CodePers { get; set; }
        public Nullable<int> CodeSynd { get; set; }
        public Nullable<double> SuperficieLocal { get; set; }
        public Nullable<int> NbrPieceLocal { get; set; }
        public Nullable<int> NbrChambreLocal { get; set; }
        public string TitreLocal { get; set; }
        public string DescrLocal { get; set; }
        public Nullable<int> MeubleLocal { get; set; }
        public Nullable<double> PrixRefLocationLocal { get; set; }
        public Nullable<int> ServiceLocal { get; set; }
        public Nullable<int> Staut { get; set; }
        public Nullable<bool> rezCh { get; set; }
        public Nullable<bool> Interphone { get; set; }
        public Nullable<bool> Parking { get; set; }
        public Nullable<bool> Garage { get; set; }
        public Nullable<bool> Jardin { get; set; }
        public Nullable<System.DateTime> DateDDispo { get; set; }
        public Nullable<System.DateTime> DateFDispo { get; set; }
        public Nullable<int> NumLocal { get; set; }
        public Nullable<int> RefCodeLocal { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        public virtual ICollection<ContratLocation> ContratLocations { get; set; }
        public virtual ICollection<Depense> Depenses { get; set; }
        public virtual Personne Personne { get; set; }
        public virtual Syndic Syndic { get; set; }
        public virtual TypeLocal TypeLocal { get; set; }
        public virtual Immeuble Immeuble { get; set; }
    }
}
