//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omni.Agence.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.MenuItem1 = new HashSet<MenuItem>();
        }
    
        public int id { get; set; }
        public string Titre { get; set; }
        public string HtmlText { get; set; }
        public string RowUrl { get; set; }
        public string CssClass { get; set; }
        public string Roles { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public Nullable<int> Order { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
    
        public virtual ICollection<MenuItem> MenuItem1 { get; set; }
        public virtual MenuItem MenuItem2 { get; set; }
    }
}
