//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omni.Agence.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgenceEntities : DbContext
    {
        public AgenceEntities()
            : base("name=AgenceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresse> Adresses { get; set; }
        public virtual DbSet<Concierge> Concierges { get; set; }
        public virtual DbSet<ContratLocation> ContratLocations { get; set; }
        public virtual DbSet<Depense> Depenses { get; set; }
        public virtual DbSet<EtatPaiement> EtatPaiements { get; set; }
        public virtual DbSet<Immeuble> Immeubles { get; set; }
        public virtual DbSet<Local> Locals { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<PaiementLoyer> PaiementLoyers { get; set; }
        public virtual DbSet<Personne> Personnes { get; set; }
        public virtual DbSet<Syndic> Syndics { get; set; }
        public virtual DbSet<TypeDesignationDepense> TypeDesignationDepenses { get; set; }
        public virtual DbSet<TypeLocal> TypeLocals { get; set; }
        public virtual DbSet<TypeOp> TypeOps { get; set; }
        public virtual DbSet<TypePersonne> TypePersonnes { get; set; }
        public virtual DbSet<Augementation> Augementations { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
