//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omni.Agence.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public Operation()
        {
            this.EtatPaiements = new HashSet<EtatPaiement>();
        }
    
        public int codeOp { get; set; }
        public Nullable<int> CodePers { get; set; }
        public int codeType { get; set; }
        public Nullable<double> montant { get; set; }
        public Nullable<System.DateTime> dateOp { get; set; }
        public string Commentaire { get; set; }
    
        public virtual Depense Depense { get; set; }
        public virtual ICollection<EtatPaiement> EtatPaiements { get; set; }
        public virtual Personne Personne { get; set; }
        public virtual TypeOp TypeOp { get; set; }
        public virtual PaiementLoyer PaiementLoyer { get; set; }
    }
}
