//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omni.Agence.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personne
    {
        public Personne()
        {
            this.ContratLocations = new HashSet<ContratLocation>();
            this.Locals = new HashSet<Local>();
            this.Operations = new HashSet<Operation>();
            this.Immeubles = new HashSet<Immeuble>();
        }
    
        public int CodePers { get; set; }
        public int CodeTypePersonne { get; set; }
        public int NumAdresse { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string nationalite { get; set; }
        public Nullable<int> sexe { get; set; }
        public string situationMatrimonial { get; set; }
        public string numPassport { get; set; }
        public string cin { get; set; }
        public string raisonSocial { get; set; }
        public string employeur { get; set; }
        public string identifiantFiscale { get; set; }
        public string nPatente { get; set; }
        public string rc { get; set; }
        public string activite { get; set; }
        public string fonction { get; set; }
        public string carteSejour { get; set; }
        public string TelFixPers { get; set; }
        public string TelMobilPers { get; set; }
        public string TelPers3 { get; set; }
        public string EmailPers { get; set; }
        public string FaxPers { get; set; }
        public Nullable<double> Solde { get; set; }
        //public Nullable<System.DateTime> DateNaiss { get; set; }
        public Nullable<int> RefCodePers { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        public virtual ICollection<ContratLocation> ContratLocations { get; set; }
        public virtual ICollection<Local> Locals { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual TypePersonne TypePersonne { get; set; }
        public virtual ICollection<Immeuble> Immeubles { get; set; }
    }
}
